export const INSTRUMENT_TYPES = {
  BUTTON: 'BUTTON',
  CHECKBOX: 'CHECKBOX',
  KEYBOARD: 'KEYBOARD',
  LIST: 'LIST',
  TEXT_AREA: 'TEXT_AREA',
  TEXT_BOX: 'TEXT_BOX',
  UI_ELEMENT: 'UI_ELEMENT',
  URL: 'URL',
};
